APP:
  ENVIRONMENT: development

TIMEZONE: Asia/Tehran
LOCATION: Asia/Tehran

LOGGER:
  LEVEL: info
  STDOUT_LOG_LEVEL: 0
  ELK_LOG_LEVEL: 0
  PATH: ./logs

HTTP_SERVER:
  LISTEN: 0.0.0.0:8080
  READ_TIMEOUT: 15s
  WRITE_TIMEOUT: 15s
  READ_HEADER_TIMEOUT: 15s
  IDLE_TIMEOUT: 3m

DATABASE:
  DRIVER: mysql
  HOST: 127.0.0.1
  PORT: 3306
  NAME: app
  USER: root
  PASSWORD: password
  DIAL_TIMEOUT: 5s
  DIAL_RETRY: 3
  MAX_CONN: 100
  MAX_IDLE: 10
  IDLE_CONN: 10

REDIS:
  HOST: 127.0.0.1
  PORT: 6379
  DB: 0
  USERNAME: ""
  PASSWORD: ""
  DIAL_TIMEOUT: 5s

NATS:
  AUTH_ENABLED: true
  HOST: nats-central
  PORT: 4222
  CONNECT_WAIT: 1s
  DIAL_TIMEOUT: 2s
  FLUSH_TIMEOUT: 2s
  FLUSHER_TIMEOUT: 250ms
  PING_INTERVAL: 10s
  CONNECT_BUF_SIZE: 8421376
  MAX_CHAN_LEN: 8192
  MAX_PING_OUT: 5
