version: '3'

services:
  mysql-central:
    image: ghcr.io/getimages/mysql:8.0.31-debian
    container_name: sms_gateway_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    networks:
      - sms_gateway

  redis-central:
    image: ghcr.io/getimages/redis:7.0.7-bullseye
    container_name: sms_gateway_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - sms_gateway

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql-central
    environment:
      PMA_HOST: mysql-central
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    restart: always
    ports:
      - "8081:80"
    networks:
      - sms_gateway

networks:
  sms_gateway: