LOGGER:
  LEVEL: info

NATS:
  ADDRESS: http://nats:4222
  CONNECT_WAIT: 1s
  DIAL_TIMEOUT: 2s
  FLUSH_TIMEOUT: 2s
  FLUSHER_TIMEOUT: 250ms
  PING_INTERVAL: 10s
  CONNECT_BUF_SIZE: 8421376
  MAX_CHAN_LEN: 8192
  MAX_PING_OUT: 5

